### PR TITLE
Fibonacci_series_without_recursion #1

### PR DESCRIPTION
**Pull request by Mystery-2-Dev**
#1 
ADDED fibonacci series program without recursion using  ruby language...

### CODE REVIEW

**Comment by twozero88** [comment]
- Set N=10. Will merge it

**Comment by Mystery-2-Dev** [comment]
IN THIS PROGRAM WHY TO SET N=10 BECAUSE I TAKES INPUT FROM USER AND THEM IT SHOWS OUTPUT  ACCORDING TO THAT

**Comment by Mystery-2-Dev** [comment]
WHERE I HAVE TO SET

**Comment by Mystery-2-Dev** [comment]
Capture


pls see this
how this program works

**Comment by twozero88** [comment]
I checked it. The repo says program to print 10 of the series.

**Comment by twozero88** [comment]
Also add it to a folder named Ruby

**Comment by Mystery-2-Dev** [comment]
anything else

**Comment by Mystery-2-Dev** [comment]
can you pls label as hacktober accepted

**Pull request merged**
