### PR TITLE
Fibonacci Series | Java

### PR DESCRIPTION
**Pull request by govindraj111**
Time Complexity: O(2N)
Auxiliary Space: O(1)

Steps: 
Screenshot from 2020-10-07 00-03-00

### CODE REVIEW

**Comment by pfaffenrodt** [comment]
@govindraj111 pls make it more enterprise with min 5 classes

**Comment by twozero88** [comment]
- Set N = 10
- Add public to FibonacciSeries

**Comment by govindraj111** [comment]
@twozero88 Done!

**Comment by govindraj111** [comment]
@twozero88 would request you to label this PR as **hacktoberfest-accepted**

**Comment by govindraj111** [comment]
>> **Hey, an update from hactoberfest states that the PR should be labeled as ‘hacktoberfest-accepted’ by a maintainer.**
Screenshot from 2020-10-16 08-04-27
Screenshot from 2020-10-16 08-06-57

>> **Please label this PR as hacktoberfest-accepted**
hacktoberfest-label-add-gif-min

**Pull request merged**
